---
- hosts: ubuntu
  become: true
  tasks:
    - name: update repositories cache and install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        update_cache: yes
    - name: enable and start qemu-guest-agent
      ansible.builtin.systemd_service:
        state: started
        enabled: true
        name: qemu-guest-agent
